version: '3'

services:

  djangoapp:
    build: .
    volumes:
      - .:/opt/services/djangoapp/src
      - static_volume:/opt/services/djangoapp/src/hello/static  # <-- bind the static volume
    networks:  # <-- here
      - nginx_network
      - hellodb_network
    depends_on:  # <-- wait for db to be "ready" before starting the app
      - hellodb

  nginx:
    image: nginx:1.14.1
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/djangoapp/src/hello/static  # <-- bind the static volume
    depends_on:  # <-- wait for djangoapp to be "ready" before starting this service
      - djangoapp
    networks:  # <-- here
      - nginx_network


  hellodb:  # <-- IMPORTANT: same name as in DATABASES setting, otherwise Django won't find the database!
    image: postgres:10.6
    env_file:  # <-- we use the previously defined values
      - config/db/hellodb_env
    networks:  # <-- connect to the bridge
      - hellodb_network
    volumes:
      - hellodb_volume:/var/lib/postgresql/data


networks:  # <-- and here
  nginx_network:
    driver: bridge 
  hellodb_network:
    driver: bridge


volumes:
  hellodb_volume:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume

